# Generated by Django 2.0.1 on 2018-02-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ask',
            new_name='askstories',
        ),
        migrations.RenameModel(
            old_name='job',
            new_name='jobstories',
        ),
        migrations.RenameModel(
            old_name='new',
            new_name='newstories',
        ),
        migrations.RenameModel(
            old_name='show',
            new_name='showstories',
        ),
    ]
