# Generated by Django 2.0.1 on 2018-02-10 15:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180206_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askstories',
            name='stories_ptr',
        ),
        migrations.RemoveField(
            model_name='jobstories',
            name='stories_ptr',
        ),
        migrations.RemoveField(
            model_name='newstories',
            name='stories_ptr',
        ),
        migrations.RemoveField(
            model_name='showstories',
            name='stories_ptr',
        ),
        migrations.AddField(
            model_name='askstories',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='askstories',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='jobstories',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jobstories',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='newstories',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='newstories',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='showstories',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='showstories',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Stories',
        ),
    ]
